const actionTypes = {
    SET_PRODUCT : 'SET_PRODUCT',
    SELECTED_PRODUCT : 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT : 'REMOVE_SELECTED_PRODUCT',
    FILTER_PRODUCTS: 'FILTER_PRODUCTS',
    ADD_TO_CART: 'ADD_TO_CART'
}

export default actionTypes;